# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12bad2547619fcd14b6b748edf1d4c8846a9ecbe01bde5e13c1f3a4537fb655217829f4766aff1ee1f421aa2266f67800e50b9f96952c65d7597a94f76dd7182

test:
  secret_key_base: 1090a273c360d22b84ef2a91b691f153a1b67a84c874b9471ed07745c1d6a8b2b419f6f2b1bf9bc917d4521fd23c796d7d059b3cd19993643995a9883bdf6aef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
